name:                ciphers
version:             0.1.0.0
github:              "zsvenczel/ciphers"
license:             BSD3
author:              "zsvenczel"
maintainer:          "venczel.zsombor@gmail.com"
copyright:           "2018 Venczel Zsombor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Toy

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zsvenczel/ciphers#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ciphers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ciphers

tests:
  ciphers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ciphers
